### ISSUE TITLE
WMI plugin error in combination with LS 2.3.x ?

### ISSUE THREAD

**Issue by githubmui** [logstash-plugins/logstash-input-wmi#12]
Hi,
I have got a problem with the WMI plugin:
1) Download LS 2.3.1 or LS 2.3.2 under my Windows 7 SP1 (JDK=1.7.0.67)
2) Unzip it and install WMI plugin with command "logstash-plugin install logstash-input-wmi"
3) After successful installation I used following standard config file:
#################################
input {
	wmi {
		query => "select * from Win32_Process"
		interval => 30
	}
}
filter {}
output {  stdout{codec=>rubydebug} }
#################################
4) Got always error: 
Pipeline aborted due to error {:exception=>#<NoMethodError: undefined method `value' for nil:NilClass>, :backtrace=>["C:/test/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-input-wmi-2.0.5-java/lib/logstash/inputs/wmi.rb:65:in `register'", "C:/test/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:330:in `start_inputs'", "org/jruby/RubyArray.java:1613:in `each'", "C:/test/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:329:in `start_inputs'", "C:/test/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:180:in `start_workers'", "C:/test/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:136:in `run'", "C:/test/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/agent.rb:465:in `start_pipeline'"], :level=>:error}

Thx in advance!

**Comment by oleg-mc** [comment]
Tried logstash-5.1.1 with the same config and got the same error.
+ 1 to the issue

**Comment by jiangjiugang** [comment]
The same config with logstash-6.4.0 and got the same error. How can I solve this problem?
